tinyMCE.addI18n('en',{
desc:"Insert Letter Widget",
title:"eTapestry Letter Widgets",
entryList:"Entry List",
entryListDesc:"This widget allows you to set up a table to display specific details about each journal entry in your query. You can choose the columns that you would like to display for these entries just as you would in a report. Additionally, if you choose to group your documents by Account or Household, this widget becomes a table that lists each journal entry for the specific account or household. This is an excellent way to list out transactions for an annual receipt, a thank you letter for multiple gifts, or any list of journal entry items that you'd like to include in your correspondence with donors.",
pledgeSchedule:"Pledge Schedule",
pledgeScheduleDesc:"This widget displays all scheduled payment dates and amounts, as well as the dates and amounts for any payments received, for the Pledges that you've included in your query. At the bottom of the list of scheduled and received payments, the total amount of the pledge and the total amount paid to date display, allowing you to keep your donors up-to-date on the status of their pledges.",
agapeGiftList:"Segmented Gift List (Agape)",
agapeGiftListDesc:"This is an Entry List that displays the Received information for transactions in your database with added detail information for segmented transactions.",
orderDetails:"Order Details",
orderDetailsDesc:"This widget displays all Order Details including Shipping Information, Billing Information, Order Summary, and Payment Information.",
ecommerceDetails:"eCommerce Details",
ecommerceDetailsDesc:"This widget displays all the main details of an eCommerce submission including Name, Address, Email, Phone, and Transaction Information (if necessary).",
accountPhoto:"Account Photo",
accountPhotoDesc:"Insert the account's photo into the document. Photos can be uploaded from the Home page of an account. This feature is only available when generating PDF and Word documents!",
donorLoyaltyLink:"Donor Loyalty Link",
donorLoyaltyLinkDesc:"This widget creates a link to your Donor Loyalty survey page. After selecting this widget, you'll be prompted to fill in the text that you'd like the link to display (for example, 'Click here to access our survey'). The link will display your text to the recipient, and when clicked, it will direct the recipient to the correct Donor Loyalty survey screen so that their survey answers will be stored on the correct eTapestry account.",
addAnotherColumn:"Add Another Column",
display:"Display",
format:"Format",
aggregate:"Aggregate",
sort:"Sort",
no:"No",
ascending:"Ascending",
descending:"Descending",
category:"Category",
field:"Field",
select:"Select",
options:"Options",
none:"None",
sum:"Sum",
avg:"Avg",
min:"Min",
max:"Max",
yearToDate:"Year to Date",
oneYearAgo:"One Year Ago",
twoYearAgo:"Two Year Ago",
threeYearAgo:"Three Year Ago",
fourYearAgo:"Four Year Ago",
fiveYearAgo:"Five Year Ago",
fiscalYearToDate:"Fiscal Year to Date",
fiscalOneYearAgo:"Fiscal One Year Ago",
fiscalTwoYearAgo:"Fiscal Two Year Ago",
fiscalThreeYearAgo:"Fiscal Three Year Ago",
fiscalFourYearAgo:"Fiscal Four Year Ago",
fiscalFiveYearAgo:"Fiscal Five Year Ago",
first:"First",
second:"Second",
third:"Third",
fourth:"Fourth",
fifth:"Fifth",
last:"Last",
align:"Align",
auto:"Auto",
left:"Left",
right:"Right",
center:"Center",
noOptionsWarning:"There are no configurable options available for this widget.",
pledgeScheduleInsert:"If you would like to use the Pledge Schedule widget, simply click Insert.",
agapeGiftListInsert:"If you would like to use the Pledge Schedule widget, simply click Insert.",
accountPhotoInsert:"If you would like to use the Account Photo widget, simply click Insert.",
orderDetailsInsert:"If you would like to use the Order Details widget, simply click Insert.",
ecommerceDetailsInsert:"If you would like to use the Ecommerce Details widget, simply click Insert.",
textToDisplayInLink:"What text would you like the link to display?",
insert: "Insert",
cancel: "Cancel",
update: "Update"
});
