tinyMCE.addI18n('en',{
mergetags_desc:"Insert eTapestry Merge Value",
title:"eTapestry Merge Values",
fieldToInsert:"Field to Insert",
none:"None",
sum:"Sum",
avg:"Avg",
min:"Min",
max:"Max",
yearToDate:"Year to Date",
oneYearAgo:"One Year Ago",
twoYearAgo:"Two Year Ago",
threeYearAgo:"Three Year Ago",
fourYearAgo:"Four Year Ago",
fiveYearAgo:"Five Year Ago",
fiscalYearToDate:"Fiscal Year to Date",
fiscalOneYearAgo:"Fiscal One Year Ago",
fiscalTwoYearAgo:"Fiscal Two Year Ago",
fiscalThreeYearAgo:"Fiscal Three Year Ago",
fiscalFourYearAgo:"Fiscal Four Year Ago",
fiscalFiveYearAgo:"Fiscal Five Year Ago",
first:"First",
second:"Second",
third:"Third",
fourth:"Fourth",
fifth:"Fifth",
last:"Last",
aggregate:"Aggregate",
category:"Category",
field:"Field",
fields:"Fields",
options:"Options",
search:"Search",
format:"Format",
search_three_chars:"Your search criteria must have at least 3 characters",
no_results_found:"No results found",
defaultValue:"Default Value",
insert: "Insert",
cancel: "Cancel",
update: "Update"
});
